#+TITLE:     annotSnpStats: a package for annotated SnpMatrix objects
#+AUTHOR:    Chris Wallace
#+EMAIL:     chris.wallace@cimr.cam.ac.uk
#+DATE:      2013-05-22 Wed
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:(not LOGBOOK) todo:t pri:nil tags:t

#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:

#+latex_header: \usepackage{fullpage}
#+latex: %\VignetteIndexEntry{Colocalisation analysis}

#+begin_html
<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Colocalisation vignette}
-->
#+end_html

* Introduction

=annotSnpStats= defines the =aSnpMatrix= class which extends the
=SnpMatrix= class from =snpStats= by aligning two dataframes contain
SNP (column) specific and sample (row) specific information.
Subsetting, binding etc can then be carried out keeping these
additional information aligned.

* Example

Use some example data from the =snpStats= package to define some new
=aSnpMatrix= objects and play with them.

** Create new objects
#+begin_src R :ravel 
library(snpStats)
library(annotSnpStats)
data(testdata, package="snpStats")
i1 <- 1:20
j1 <- 1:100

## initialize
rownames(Asnps) <- colnames(Autosomes)
rownames(Xsnps) <- colnames(Xchromosome)

as11 <- new("aSnpMatrix",
                 .Data=Autosomes[i1,j1],
                 snps=Asnps[j1,,drop=FALSE],
                 samples=subject.data[i1,])
as11
#+end_src

** Access annotation objects

#+begin_src R :ravel 
head(as11@snps)
head(as11@samples)
#+end_src

** Use in place of regular SnpMatrix objects

=snpStats= functions should all work with =aSnpMatrix= objects

#+begin_src R :ravel 
summary(as11)
#+end_src

** Subsetting

Subsetting subsets both the =SnpMatrix= and the annotation objects

#+begin_src R :ravel 
asub <- as11[1:3,1:5]
dim(as11)
dim(asub)
nrow(as11@snps)
nrow(asub@snps)
nrow(as11@samples)
nrow(asub@samples)
#+end_src

** Binding
You can bind =aSnpMatrix= objects using the S4 =cbind2= and
=rbind2= methods:

#+begin_src R :ravel 
i2 <- 21:40
j2 <- 101:200
as12 <- new("aSnpMatrix",
                 .Data=Autosomes[i1,j2],
                 snps=Asnps[j2,,drop=FALSE],
                 samples=subject.data[i1,])
as21 <- new("aSnpMatrix",
                 .Data=Autosomes[i2,j1],
                 snps=Asnps[j1,,drop=FALSE],
                 samples=subject.data[i2,])

cbind2(as11,as12)
rbind2(as11,as21)
#+end_src

* Other functions

A few other handy functions are included. See the individual help
pages for more detail on these.

- =dups= finds indices of possible sample duplications between two
  aSnpStats objects
- =mismatch.count= quickly counts mismatched genotypes between pairs
  of individuals
- =sample.match= identifies indices of overlapping samples in two
  aSnpMatrix objects.  By default, match is on =rownames(x@samples)=,
  =rownames(y@samples)=.
- =snp.match= identifies indices of overlapping samples in two
  aSnpMatrix objects.  By default, match is on =rownames(x@snps)=,
  =rownames(y@snps)=.
- =snp.trim= drops SNPs from an annotSnpStats object according to SNP qc summary
  stats
 
