% Created 2014-09-25 Thu 20:36
\documentclass[11pt]{article}
\usepackage{amsmath}
\usepackage{fixltx2e}
\usepackage{graphicx}
\usepackage{longtable}
\usepackage{float}
\usepackage{wrapfig}
\usepackage{soul}
\usepackage{textcomp}
\usepackage{marvosym}
\usepackage{wasysym}
\usepackage{latexsym}
\usepackage{amssymb}
\usepackage{amstext}
\usepackage{hyperref}
\tolerance=1000
\usepackage{fullpage}
\author{Chris Wallace}
\date{2013-05-22 Wed}
\title{annotSnpStats: a package for annotated SnpMatrix objects}
\hypersetup{
  pdfkeywords={},
  pdfsubject={},
  pdfcreator={Emacs 24.3.1 (Org mode 8.2.7c)}}
\begin{document}

\maketitle
\tableofcontents

%\VignetteIndexEntry{annotated SnpMatrix objects}

\section{Introduction}
\label{sec-1}

\texttt{annotSnpStats} defines the \texttt{aSnpMatrix} and \texttt{aXSnpMatrix} classes
which extend the \texttt{SnpMatrix} and \texttt{XSnpMatrix} classes from \texttt{snpStats}
by aligning genotype data with two dataframes containing SNP (column)
specific and sample (row) specific information.  Subsetting, binding
etc can then be carried out keeping this additional information
aligned.

Various utility functions have been added which aim to make the
manipulation and merging of two or more genotype datasets as painless
and as accurate as possible.

\section{Examples}
\label{sec-2}

The advantage of using \texttt{annotSnpStats} is perhaps best seen using some
example data from the \texttt{snpStats} package to define some new
\texttt{aSnpMatrix} objects and play with them.

\subsection{Create new objects}
\label{sec-2-1}
<<>>=
library(snpStats)
library(annotSnpStats)
data(testdata, package="snpStats")
i1 <- 1:20
j1 <- 1:100

## initialize
rownames(Asnps) <- colnames(Autosomes)
rownames(Xsnps) <- colnames(Xchromosome)

as11 <- new("aSnpMatrix",
		 .Data=Autosomes[i1,j1],
		 snps=Asnps[j1,,drop=FALSE],
		 samples=subject.data[i1,])
as11
@ %def

\subsection{Access annotation objects}
\label{sec-2-2}

<<>>=
head(snps(as11))
head(samples(as11))
@ %def

\subsection{Use in place of regular SnpMatrix objects}
\label{sec-2-3}

All \texttt{snpStats} S4 methods should work with \texttt{aSnpMatrix} objects

<<>>=
summary(as11)
@ %def

However, certain \texttt{snpStats} functions do not use the S4 interface, and
inheritance then gets a bit messed up.  In that case, you may need to
explicity extract the \texttt{SnpMatrix} object.  For example, to use
snpStats's \texttt{ld} function:

<<>>=
ld(as(as11,"SnpMatrix"),depth=5,stats="R.squared")
@ %def

\subsection{Subsetting}
\label{sec-2-4}

Subsetting subsets both the \texttt{SnpMatrix} and the annotation objects

<<>>=
asub <- as11[1:3,1:5]
dim(as11)
dim(asub)
nrow(snps(as11))
nrow(snps(asub))
nrow(samples(as11))
nrow(samples(asub))
@ %def

\subsection{Binding}
\label{sec-2-5}
You can c/rbind \texttt{aSnpMatrix} objects using the S4 \texttt{cbind2} and
\texttt{rbind2} methods:

<<>>=
i2 <- 21:40
j2 <- 101:200
as12 <- new("aSnpMatrix",
		 .Data=Autosomes[i1,j2],
		 snps=Asnps[j2,,drop=FALSE],
		 samples=subject.data[i1,])
as21 <- new("aSnpMatrix",
		 .Data=Autosomes[i2,j1],
		 snps=Asnps[j1,,drop=FALSE],
		 samples=subject.data[i2,])

cbind2(as11,as12)
rbind2(as11,as21)
@ %def

\section{Allele codes}
\label{sec-3}
Genotype data is stored in a (compressed) format with 1=AA, 2=AB and
3=BB genotypes.  If you wish to merge two datasets, you need to know
what each code corresponds to.  This information should be stored in a
pair of columns in the \texttt{snps} slot of the object.  The first member
should show the base (A, C, G or T) corresponding to an AA homozygote,
and the second the base corresponding to a BB homozygote.  \texttt{aSnpStats}
functions can try and guess which columns might be storing this
information, but it is safer to specify explicitly.

<<>>=
snps(asub) <- cbind(snps(asub),a1="C",a2="G")
# set the allele codes
alleles(asub) <- c("a1","a2")
head(snps(asub))
# check the allele codes
alleles(asub)
@ %def

\section{Other functions}
\label{sec-4}

A few other handy functions are included which should make joining
multiple aSnpMatrix objects easier. See the individual help
pages for more detail on these.

\begin{itemize}
\item \texttt{dups} finds indices of possible sample duplications between two
aSnpStats objects
\item \texttt{mismatch.count} quickly counts mismatched genotypes between pairs
of individuals
\item \texttt{mismatch.count.all} quickly counts mismatched genotypes between all
possible pairs of individuals - this can be slow!
\item \texttt{sample.match} identifies indices of overlapping samples in two
aSnpMatrix objects.  By default, match is on \texttt{rownames(x@samples)},
\texttt{rownames(y@samples)}.
\item \texttt{snp.match} identifies indices of overlapping samples in two
aSnpMatrix objects.  By default, match is on \texttt{rownames(x@snps)},
\texttt{rownames(y@snps)}.
\item \texttt{snp.trim} drops SNPs from an annotSnpStats object according to SNP
qc summary stats according to user specified limits
\item \texttt{align.alleles} automates using \texttt{snpStats::switch.alleles} to ensure
numeric annotation of genotypes uses a consistent code between two
different datasets, essential to join up data.
\end{itemize}
% Emacs 24.3.1 (Org mode 8.2.7c)
\end{document}
