# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dups <- function(X, Y, maxDiff, Rtype, Rquick, null, het) {
    .Call('annotSnpStats_dups', PACKAGE = 'annotSnpStats', X, Y, maxDiff, Rtype, Rquick, null, het)
}

