# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dups <- function(X, Y, maxDiff, Rtype, Rquick, null, het) {
    .Call('annotSnpStats_dups', PACKAGE = 'annotSnpStats', X, Y, maxDiff, Rtype, Rquick, null, het)
}

asw <- function(x, w) {
    .Call('annotSnpStats_asw', PACKAGE = 'annotSnpStats', x, w)
}

